### ISSUE TITLE
Zeroise memory

### ISSUE THREAD

**Issue by karlbuys** [walletd/walletd#28]
One concern we may want to look at given the fact that WalletD handles secret keys, is that of how we zeroise memory. I'm not familiar enough with the drop mechanism Rust implements, and how it handles memory zeroing, so I'm not in a position to say whether we should be concerned about this at this stage of the project.

Any expert advice on this would be welcomed

https://docs.rs/zeroize/latest/zeroize/

**Comment by amilumibe** [comment]
Started work on this, looking into how to implement for bitcoin, reference of PR in rust-bitcoin that did not get implemented but useful discussion for how to implement: https://github.com/rust-bitcoin/rust-secp256k1/pull/262/files#diff-9cd3b5d03af9cda5af8a728d7c03ad4630b9e8d83c0eea88a4287df007bf266b

**Comment by amilumibe** [comment]
Example implementation of zeroize that could be followed for walletd: https://github.com/dalek-cryptography/ed25519-dalek
