### ISSUE TITLE
Improve test coverage to about 80% or greater

### ISSUE THREAD

**Issue by amilumibe** [walletd/walletd#35]

**Comment by devinpearson** [comment]
This needs to be broken down. This task cant be done in 400 changes or less and requires tests across the whole system, aiming for portions of the system. This is more of a milestone

**Comment by amilumibe** [comment]
Yes agree that the task needs to be broken down.. not exactly sure how to splice it into different issues. Currently PR #https://github.com/walletd/walletd/pull/63 adds more test coverage but not yet at 80% yet
