### ISSUE TITLE
Look into making 'blocking' versions of calls to blockchain using reqwest

### ISSUE THREAD

**Issue by amilumibe** [walletd/walletd#61]
https://tokio.rs/tokio/tutorial.  Tokio docs mention  under the section "When not to use Tokio"

Sending a single web request. The place where Tokio gives you an advantage is when you need to do many things at the same time. If you need to use a library intended for asynchronous Rust such as [reqwest](https://docs.rs/reqwest/), but you don't need to do a lot of things at once, you should prefer the blocking version of that library, as it will make your project simpler. Using Tokio will still work, of course, but provides no real advantage over the blocking API. If the library doesn't provide a blocking API, see [the chapter on bridging with sync code](https://tokio.rs/tokio/topics/bridging).

**Comment by devinpearson** [comment]
This needs more discussion around the value it adds across all the libraries. its been moved to a discussion
https://github.com/walletd/walletd/discussions/75
